### ISSUE TITLE
Feature request: Automatic  pretrained weight download

### ISSUE THREAD

**Issue by tarepan** [sarulab-speech/xvector_jtubespeech#3]
## Summary
'Automatic pretrained weight download' feature will help user to use this library easier.  
I test this functionality through `torch.hub`.  
Can I make a pull request?  

## Current Status
Users can install the x-vector model class through pip, but needs manual weight download (e.g. `wget`, `git clone`).  
This step needs engineering skills to ML users, so brings non-streamlined developer experience.  
This situation could prevent more widespread usage of this valuable package.  

## Cause
Manual weight download is the cause of this pain.  

## Proposal
We could use `torch.hub` system for automatic weight (and package) download.  
With this system, we can instantiate the model without any explicit model/package download as below:  

```python
model = torch.hub.load("tarepan/xvector_jtubespeech-official:feature/hub", "xvector", trust_repo=True)
```
`torch.hub.load` automatically:

- pull the `xvector_jtubespeech` package from github
- download the `xvector.pth` file from github
- Access `_XVector` class and instantiate it
- load state_dict

I wrote basic feature of `torch.hub` in my [fork](https://github.com/tarepan/xvector_jtubespeech-official/tree/feature/hub).  
If you kindly consider reviewing this feature, I am grad to make a pull request.  

## Notes
When I tested ,this x-vector model is so good at Japanese speaker classification.  
Thanks for your great model & package.

**Comment by vebmaylrie** [comment]
Sorry for my late reply. 
> Can I make a pull request?
Yes. please!
